//==================================================
// This file contains the Excluded objects
// Generated By User: ICer
// Format Version: 2
// Date: Thu May 12 02:19:11 2022
// ExclMode: default
//==================================================
CHECKSUM: "1351411110 3589045007"
INSTANCE: axi_bus_top
Toggle prdata0 "reg prdata0"
Toggle prdata1 "reg prdata1"
Toggle prdata2 "reg prdata2"
CHECKSUM: "3122789476 3965889079"
INSTANCE: axi_bus_top.DW_axi_x2p_u.U_APB_MASTER.U_x2ps_addr
Toggle cmd_addr "net cmd_addr[31:0]"
Toggle cmd_type "net cmd_type[1:0]"
Toggle cmd_size "net cmd_size[2:0]"
Toggle paddr "reg paddr[31:0]"
Toggle next_paddr "net next_paddr[31:0]"
Toggle next_address "reg next_address[31:0]"
Toggle address_temp "reg address_temp[31:0]"
Toggle address "reg address[31:0]"
Toggle next_address_from_set "reg next_address_from_set[31:0]"
Toggle next_base_address_from_set "reg next_base_address_from_set[31:0]"
Toggle next_address_from_incr_base "reg next_address_from_incr_base[31:0]"
Toggle next_base_address_from_incr_base "reg next_base_address_from_incr_base[31:0]"
Toggle next_address_from_incr "reg next_address_from_incr[31:0]"
Toggle next_base_address_from_incr "reg next_base_address_from_incr[31:0]"
Toggle base_addr "reg base_addr[31:0]"
Toggle next_base_addr "reg next_base_addr[31:0]"
Toggle addr_lsb_mask "reg addr_lsb_mask[31:0]"
Toggle base_addr_inc "reg base_addr_inc[7:0]"
Toggle wrap_error "reg wrap_error"
CHECKSUM: "2220131992 993209771"
INSTANCE: axi_bus_top.DW_axi_x2p_u.U_APB_MASTER.U_x2ps_addr.U_apb_psel
Toggle psel_addr "net psel_addr[31:10]"
Toggle paddr "net paddr[31:10]"
CHECKSUM: "3010218294 2858676122"
INSTANCE: axi_bus_top.DW_axi_x2p_u.U_APB_MASTER.U_x2ps_ctrl
Toggle selected_strobes "net selected_strobes[3:0]"
Toggle resp_rdy_n "net resp_rdy_n"
CHECKSUM: "3008444807 1578323066"
INSTANCE: axi_bus_top.DW_axi_x2p_u.U_APB_MASTER.U_x2ps_first_last_strb
Toggle last_strobe "reg last_strobe[7:0]"
Toggle last_strobe_ns "net last_strobe_ns[7:0]"
CHECKSUM: "3892737307 2638872202"
INSTANCE: axi_bus_top.DW_axi_x2p_u.U_APB_MASTER.U_x2ps_pack
Toggle apb_addr "net apb_addr[31:0]"
Toggle cmd_id "net cmd_id[7:0]"
Toggle axi_id "reg axi_id[7:0]"
CHECKSUM: "668708421 3189365313"
INSTANCE: axi_bus_top.DW_axi_x2p_u.U_APB_MASTER.U_x2ps_resp
Toggle cmd_id "net cmd_id[7:0]"
Toggle resp_rdy_n "net resp_rdy_n"
Toggle resp_id "net resp_id[7:0]"
Toggle saved_cmd_id "reg saved_cmd_id[7:0]"
Toggle next_saved_cmd_id "net next_saved_cmd_id[7:0]"
CHECKSUM: "783313477 1035302342"
INSTANCE: axi_bus_top.DW_axi_x2p_u.U_APB_MASTER.U_x2ps_unpack
Toggle write_buff_strobes "net write_buff_strobes[3:0]"
Toggle next_apb_wd_sel "net next_apb_wd_sel[7:0]"
Toggle selected_strobes "net selected_strobes[3:0]"
Toggle selected_strobes_ns "reg selected_strobes_ns[3:0]"
CHECKSUM: "2301581421 114414442"
INSTANCE: axi_bus_top.DW_axi_x2p_u.U_APB_MASTER
Toggle hcmd_queue_wd_int "net hcmd_queue_wd_int[49:0]"
Toggle hresp_rdy_int_n "net hresp_rdy_int_n"
Toggle cmd_queue_addr "net cmd_queue_addr[31:0]"
Toggle cmd_id "net cmd_id[7:0]"
Toggle conditioned_write_strobes "net conditioned_write_strobes[3:0]"
CHECKSUM: "2307373657 1563124670"
INSTANCE: axi_bus_top.DW_axi_x2p_u.U_AXI_SLAVE
Toggle awid "net awid[7:0]"
Toggle awaddr "net awaddr[31:0]"
Toggle awsize "net awsize[2:0]"
Toggle awburst "net awburst[1:0]"
Toggle wstrb "net wstrb[3:0]"
Toggle bid "net bid[7:0]"
Toggle bresp "net bresp[1:0]"
Toggle cmd_queue_wd "reg cmd_queue_wd[49:0]"
Toggle cmd_queue_rdy_n "net cmd_queue_rdy_n"
Toggle pop_resp_word "net pop_resp_word[8:0]"
Toggle write_buffer_wd "net write_buffer_wd[36:0]"
Toggle arsize "net arsize[2:0]"
Toggle rid "net rid[7:0]"
Toggle rresp "net rresp[1:0]"
Toggle arid_int "net arid_int[7:0]"
Toggle wr_cmd_queue_wd "reg wr_cmd_queue_wd[49:0]"
Toggle rd_cmd_queue_wd "reg rd_cmd_queue_wd[49:0]"
